fitness/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.index,name='index'),
    
    path('informacion_usuario/',views.informacion_usuario,name='informacion_usuario'),
    path('perfil_usuario/<int:id_usuario>/',views.perfil_usuario,name='perfil_usuario'),
    path('entrenamientos',views.entrenamiento_aerobico,name='entrenamientos'),
    path('usuario_H',views.usuario_con_h,name='usuario_H'),
    path('entrenamiento/<int:entrenamiento_id>/comentarios/', views.comentarios_entrenamiento, name='comentarios_entrenamiento'),
    path('comentarios/<int:anyo_comentario>/<int:mes_comentario>',views.comentarios_fecha,name='comentarios_fecha'),
    path('categoria/',views.categoria_lisos,name='categoria_lisos'),
    path('lista_entrenamientos',views.lista_entrenamientos,name='lista_entrenamientos'),
    path('grupo_muscular/<str:grupo_muscular>/', views.grupo_muscular,name='grupo_muscular'),
    path('usuarios_sin_comentarios/', views.usuarios_sin_comentarios, name='usuarios_sin_comentarios'),
    path('historial_ejercicios/<int:usuario_id>/', views.historial_ejercicios_usuario, name='historial_ejercicios_usuario'),
    path('ultimo_voto/<int:id_ejercicio>',views.ultimo_voto,name='ultimo_voto'),
    path('banco_tipo/<str:texto>',views.cuentas_bancarias,name='banco_tipo'),
    path('puntuacion_tres/<int:id_usuario>',views.puntuacion_tres,name='puntuacion_tres'),
    path('usuarios_sin_votos',views.usuarios_sin_votos,name='usuarios_sin_votos'),
    
    #URL DE EJERCICIO:
    path('create',views.ejercicio_crear,name='create'),
    path('ejercicio_buscar/',views.ejercicio_buscar,name='ejercicio_buscar'),
    path('ejercicio_busqueda_avanzada/',views.ejercicio_busqueda_avanzada,name='ejercicio_busqueda_avanzada'),
    path('ejercicios/listar',views.lista_ejercicios,name='lista_ejercicios'),
    path('ejercicio/editar/<int:ejercicio_id>/',views.ejercicio_editar,name='ejercicio_editar'),
    path('ejercicio/eliminar/<int:ejercicio_id>/',views.ejercicio_eliminar,name='ejercicio_eliminar'),
    path('ejercicio/<int:ejercicio_id>/',views.ejercicio_mostrar,name='ejercicio_mostrar'),
    
    #URL DE ENTRENAMIENTOS:
    path('create_entrenamiento',views.entrenamiento_create,name='create_entrenamiento'),
    path('entrenamiento_buscar/',views.entrenamiento_buscar,name='entrenamiento_buscar'),
    path('entrenamiento_busqueda_avanzada/',views.entrenamiento_buscar_avanzado,name='entrenamiento_busqueda_avanzada'),
    path('listar_entrenamiento',views.lista_entrenamientos,name='listar_entrenamientos'),
     path('entrenamiento/<int:entrenamiento_id>/',views.entrenamiento_mostrar,name='entrenamiento_mostrar'),
     path('entrenamiento/editar/<int:entrenamiento_id>/',views.entrenamiento_editar,name='entrenamiento_editar'),
     path('entrenamiento/eliminar/<int:entrenamiento_id>/',views.entrenamiento_eliminar,name='entrenamiento_eliminar'),
     
     
     #URL PLAN_ENTRENAMIENTO:
    path('plan/listar',views.lista_plan,name='lista_plan'),
     path('create-plan',views.plan_create,name='create-plan'),
     path('plan_buscar/',views.plan_buscar,name='plan_buscar'),
    path('plan_busqueda_avanzada/',views.plan_busqueda_avanzada,name='plan_busqueda_avanzada'),
    path('plan/<int:plan_id>/',views.mostrar_plan,name='mostrar_plan'),
    path('plan/editar/<int:plan_id>/',views.plan_editar,name='plan_editar'),
    path('plan/eliminar/<int:plan_id>/',views.plan_eliminar,name='plan_eliminar'),
    
    
    
    #URL RUTINA:
    path('rutina/listar',views.lista_rutina,name='lista_rutina'),
    path('create-rutina',views.rutina_create,name='create-rutina'),
    path('rutina_buscar/',views.rutina_buscar,name='rutina_buscar'),
    path('rutina_busqueda_avanzada/',views.rutina_busqueda_avanzada,name='rutina_busqueda_avanzada'),
    path('rutina/<int:rutina_id>/',views.mostrar_rutina,name='mostrar_rutina'),
    path('rutina/editar/<int:rutina_id>/',views.rutina_editar,name='rutina_editar'),
    path('rutina/eliminar/<int:rutina_id>/',views.rutina_eliminar,name='rutina_eliminar'),
    
    #URL COMENTARIOS:
    path('comentario/listar',views.lista_comentarios,name='lista_comentarios'),
    path('create-comentario',views.comentario_create,name='create-comentario'),
    path('comentario_buscar/',views.comentario_buscar,name='comentario_buscar'),
    path('comentario_busqueda_avanzada/',views.comentario_busqueda_avanzada,name='comentario_busqueda_avanzada'),
    path('comentario/editar/<int:comentario_id>',views.comentario_editar,name='comentario_editar'),
    path('comentario/<int:comentario_id>/',views.mostrar_comentario,name='mostrar_comentario'),
    path('comentario/eliminar/<int:comentario_id>/',views.comentario_eliminar,name='comentario_eliminar'),
    
    
    #URL SUSCRIPCION:
    path('suscripcion/listar',views.lista_suscripcion,name='lista_suscripcion'),
    path('create-suscripcion',views.suscripcion_create,name='create-suscripcion'),
    path('suscripcion<int:suscripcion_id>/',views.suscripcion_mostrar,name='mostrar_suscripcion'),
    path('suscripcion_buscar/',views.suscripcion_buscar,name='suscripcion_buscar'),
    path('suscripcion_busqueda_avanzada/',views.suscripcion_busqueda_avanzada,name='suscripcion_busqueda_avanzada'),
    path('suscripcion/editar/<int:suscripcion_id>',views.suscripcion_editar,name='suscripcion_editar'),
    path('suscripcion/eliminar/<int:suscripcion_id>/',views.suscripcion_eliminar,name='suscripcion_eliminar'),
    
    path('registrar',views.registrar_usuario,name='registrar_usuario'),
    
    #URL EXAMEN:
    path('promocion/<int:promocion_id>/',views.mostrar_promocion,name='promocion_mostrar'),
    path('promocion/listar',views.lista_promocion,name='lista_promocion'),
    path('create-promocion',views.promocion_create,name='create-promocion'),
    path('promocion/eliminar/<int:promocion_id>/',views.promocion_eliminar,name='promocion_eliminar'),
    path('plan/promocionar/<int:promocion_id>/',views.promocion_editar,name='promocion_editar'),
    path('promocion_busqueda_avanzada/',views.promocion_busqueda_avanzada,name='promocion_busqueda_avanzada'),
     
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import handler404,handler400,handler403,handler500



urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('fitness.urls')),
    path('api/v1/',include('fitness.api_urls')),
    path('oauth2/',include('oauth2_provider.urls',namespace='oauth2_provider'))
    
   
]
handler404 = 'fitness.views.mi_error_404'
handler400 = 'fitness.views.mi_error_400'
handler403 = 'fitness.views.mi_error_403'
handler500 = 'fitness.views.mi_error_500'

fitness/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Usuario(AbstractUser):
    ADMINISTRADOR = 1
    CLIENTE = 2
    ENTRENADOR = 3
    ROLES = (
        (ADMINISTRADOR, 'administardor'),
        (CLIENTE, 'cliente'),
        (ENTRENADOR, 'entrenador'),
    )
    
    rol  = models.PositiveSmallIntegerField(
        choices=ROLES,default=1
    )
    
    
class Entrenador(models.Model):
    usuario = models.OneToOneField(Usuario, 
                             on_delete = models.CASCADE)
    
    
class Suscripcion(models.Model):
    BANCOS = [
        ('CAI', 'Caixa'),
        ('BBV', 'BBVA'),
        ('UNI', 'Unicaja'),
        ('ING', 'ING España'),
    ]
    
    banco = models.CharField(
                            max_length=3,
                            choices=BANCOS,
                            default='ING',
                             )
    
    numero_cuenta = models.CharField(max_length=20)
    titular = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f"Cliente: {self.usuario.username}"
    
class Perfil_de_Usuario(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    edad = models.IntegerField()
    altura = models.FloatField()
    peso = models.FloatField()
    foto_perfil = models.ImageField(upload_to='imagenes/')
    #upload_to --> especifica la carpeta donde se van a guardar las imagenes.
    
    def __str__(self) -> str:
        return  f"Perfil de {self.usuario.username}, Edad: {self.edad}, Altura: {self.altura}, Peso: {self.peso}"
    
    

class Musculo(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre
    
class GrupoMuscular(models.Model):
    NIVEL_CHOICES = (
        ('GRANDE', 'Grupos musculares grandes'),
        ('MEDIANO', 'Grupos musculares medianos'),
        ('PEQUEÑO', 'Grupos musculares pequeños'),
    )
    
    nombre = models.CharField(max_length=50)
    nivel = models.CharField(max_length=10, choices=NIVEL_CHOICES)
    musculos = models.ManyToManyField(Musculo)

    def __str__(self):
        return self.nombre

    
class Ejercicio(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    TIPOS = [
        ('AER','Aeróbico'),
        ('FUE','Fuerza o anaeróbico'),
        ('FUN','Funcional'),
        ('HIT','Hit'),
        ('POT','Potencia'),
    ]
    tipo_ejercicio = models.CharField(max_length=3,
                            choices=TIPOS,
                            default='HIT',
                            )
    usuarios = models.ManyToManyField(Usuario, through='HistorialEjercicio')
    grupos_musculares = models.ManyToManyField(GrupoMuscular)
    imagen = models.FileField(null=True)
    #usuarios_votos = models.ManyToManyField(Usuario,through='Voto',related_name='usuarios_votos')
    
    def __str__(self):
        return self.nombre
   

class Cliente(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    ejercicios_favoritos = models.ManyToManyField(Ejercicio, through='Favoritos', related_name='ejercicios_favoritos_cliente')


class Favoritos(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    ejercicio = models.ForeignKey(Ejercicio, on_delete=models.CASCADE)


class CategoriaEjercicio(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    ejercicios = models.ManyToManyField('Ejercicio')
    
    def __str__(self) -> str:
        return self.nombre
    
class Entrenamiento(models.Model):
    TIPOS = [
        ('RES','Resistencia'),
        ('FUE','Fuerza o anaeróbico'),
        ('VEL','Velocidad'),
        ('HIT','Hit'),
        ('POT','Potencia'),
        ('POT','Potencia'),
        ('GAP','GAP'),
        ('ZUM','Zumba'),
    ]
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    descripcion= models.TextField()
    duracion = models.IntegerField()
    tipo = models.CharField(max_length=3,
                            choices=TIPOS,
                            default='HIT',
                            )
    ejercicios = models.ManyToManyField(Ejercicio,through='EntrenamientoEjercicio')
    

class EntrenamientoEjercicio(models.Model):
    entrenamiento = models.ForeignKey(Entrenamiento, on_delete=models.CASCADE)
    ejercicio = models.ForeignKey(Ejercicio, on_delete=models.CASCADE)
    repeticiones = models.IntegerField(default=0)
    peso_utilizado = models.FloatField(default=0)
    
class HistorialEjercicio(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    ejercicio = models.ForeignKey(Ejercicio, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    duracion = models.IntegerField(default=0)
    repeticiones = models.IntegerField(default=0)
    peso = models.FloatField(default=0)
    calorias = models.FloatField(default=0)

class Comentario(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    entrenamiento = models.ForeignKey(Entrenamiento, on_delete=models.CASCADE)
    texto = models.TextField()
    fecha = models.DateTimeField(default=timezone.now)

class PlanEntrenamiento(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    duracion_estimada = models.IntegerField()
    dificultad = models.CharField(max_length=20)
    entrenamientos = models.ManyToManyField('Entrenamiento', through='EntrenamientoPlan')
    fecha_inicio = models.DateTimeField(default=timezone.now)
    fecha_fin = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

class EntrenamientoPlan(models.Model):
    plan_entrenamiento = models.ForeignKey(PlanEntrenamiento, on_delete=models.CASCADE)
    entrenamiento = models.ForeignKey(Entrenamiento, on_delete=models.CASCADE)

class SeguimientoPlanEntrenamiento(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    plan_entrenamiento = models.ForeignKey(PlanEntrenamiento, on_delete=models.CASCADE)
    fecha_inicio = models.DateTimeField(default=timezone.now)
    fecha_fin = models.DateTimeField(default=timezone.now)
    progreso = models.IntegerField()

class RutinaDiaria(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    descripcion = models.TextField()
    duracion = models.IntegerField()
    ejercicios = models.ManyToManyField(Ejercicio, through='RutinaEjercicio')

class RutinaEjercicio(models.Model):
    rutina_diaria = models.ForeignKey(RutinaDiaria, on_delete=models.CASCADE)
    ejercicio = models.ForeignKey(Ejercicio, on_delete=models.CASCADE)
    
    
class Voto(models.Model):
    u_creador = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    puntuacion = models.IntegerField(default=1,
                                            validators=[
                                                MaxValueValidator(5),
                                                MinValueValidator(1)
                                            ])
    comentario = models.TextField()
    fecha = models.DateTimeField(default=timezone.now)
    #ejercicio = models.ForeignKey(Ejercicio,on_delete=models.CASCADE)
    

    
class Promocion(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    descuento = models.IntegerField(default=1,
                                            validators=[
                                                MaxValueValidator(100),
                                                MinValueValidator(0)
                                            ])
    fecha = models.DateField()
    usuario = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    

    

fitness/templates/url-anteriores/categoria_lisos.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
<br>
<h1>CATEGORÍA DE EJERCICIOS PARA MÚSCULOS LISOS:</h1>
{% endblock %}


    <h1>Categorías de Ejercicios para Músculos Lisos</h1>

{% block contenido %}
<br>
<ul>
    {% for categoria in categoria_mostrar %}
        <li>
            <p><strong>Nombre:</strong> {{ categoria.nombre }}</p>
            <p><strong>Descripción:</strong> {{ categoria.descripcion }}</p>
            <p><strong>Grupo Muscular Principal:</strong> {{ categoria.grupo_muscular_principal }}</p>
            <h3>EJERCICIOS:</h3>
            <ul>
                {% for ejercicio in categoria.ejercicios.all %}
                    <li>
                        <p><strong>Nombre:</strong> {{ ejercicio.nombre }}</p>
                        <p><strong>Descripción:</strong> {{ ejercicio.descripcion }}</p>
                        <p><strong>Tipo de Ejercicio:</strong> {{ ejercicio.tipo_ejercicio }}</p>
                        <!-- Otros campos relacionados con Ejercicio -->
                    </li>
                    <hr>
                {% endfor %}
            </ul>
        </li>
        <hr>
    {% endfor %}
</ul>
{% endblock %}

fitness/templates/url-anteriores/comentarios_entrenamiento.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
{% endblock %}
    

{% block contenido%}
<BR>
<h1>COMENTARIOS DEL ENTRENAMIENTO:</h1>
<p><i>{{ entrenamiento.nombre }}</i></p>
<br>
<ul>
    {% for comentario in comentarios %}
        <li>
            <p><strong>Usuario:</strong> {{ comentario.usuario.nombre }}</p>
            <p><strong>Fecha:</strong> {{ comentario.fecha }}</p>
            <p><strong>Comentario:</strong> {{ comentario.texto }}</p>
        </li>
        <hr>
    {% endfor %}
</ul>
{% endblock%}

fitness/templates/url-anteriores/entrenamientos_aerobicos.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
<br>
  <h2>DETALLES DE LOS ENTRENAMIENTOS ANAEROBICOS</h2>
{% endblock %}
   {% block contenido %}
   <img src="{% static 'imagenes/entrenamientos_anaerobicos.jpg'%}" width="450" height="280"></img>
   <ul>
    {% for entrenamiento in entrenamientos_mostrar %}
    <br>
        <li>
            <p><strong>Nombre:</strong>{{ entrenamiento.nombre }}</h2>
            <p><strong>Descripción:</strong> {{ entrenamiento.descripcion }}</p>
            <p><strong>Duración (minutos):</strong> {{ entrenamiento.duracion }}</p>
            <p><strong>Tipo de entrenamiento:</strong> {{ entrenamiento.get_tipo_display }}</p>
            <p><strong>Usuarios:</strong> {{ entrenamiento.usuario }}</p>
            <h3>EJERCICIOS:</h3>
            <ul> <!--Entrenamiento tiene una relacion ManytoMany con ejercicios-->
                {% for ejercicio in entrenamiento.ejercicios.all %}
                    <p><strong>Ejercicio:</strong> {{ ejercicio.nombre }}</p>
                    
                    <p><strong>Tipo:</strong>{{ ejercicio.tipo_ejercicio }}</p>
                
                {% endfor %}
            </ul>
        </li>
        <hr>
    {% endfor %}
</ul>
{% endblock %}

fitness/templates/url-anteriores/grupo_muscular.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
{% endblock %}

    
{% block contenido %}
<BR>
<h1>CATEGORÍAS DE EJERCICIOS PARA EL EL GRUPO MUSCULAR:<i>{{ grupo_muscular }}</i></h1>
<ul>
    {% for category in categories %}
    <li>
        <p><strong>Nombre:</strong>{{ category.nombre }}</p>
        <ul> 
            <strong>Ejercicios:</strong>
            {% for exercise in category.ejercicios.all %}
            <li>{{ exercise.nombre }}</li>
            {% endfor %}
        </ul>
    </li>
    <hr>
    {% endfor %}
</ul>
{% endblock %}

fitness/templates/url-anteriores/historial_ejercicios_usuario.html
<!DOCTYPE html>
<html>
<head>
    <title>Historial de Ejercicios del Usuario</title>
</head>
<body>
    <h1>Historial de Ejercicios para el Usuario: {{ usuario.nombre }}</h1>
    <ul>
        {% for ejercicio in historial_ejercicios %}
        <li>
            <strong>Fecha:</strong> {{ ejercicio.fecha }}<br>
            <strong>Ejercicio:</strong> {{ ejercicio.ejercicio.nombre }}<br>
            <strong>Repeticiones:</strong> {{ ejercicio.repeticiones }}<br>
            <strong>Peso Utilizado:</strong> {{ ejercicio.peso }}<br>
        </li>
        {% endfor %}
    </ul>
    <footer>
        <p>Pie de página &copy; 2023 Gabriela Pinzón</p>
    </footer>
</body>
</html>

fitness/templates/url-anteriores/informacion_usuario.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
<br>
<h1>Lista de Usuarios</h1>
{% endblock %}
    
{% block contenido %}
<ul>
    {% for usuario in usuario_mostrar %}
        <li>
            <p><b>ID:</b> {{ usuario.id }}</p>
            <p><b>Nombre:</b> {{ usuario.nombre }}</p>
            <p><b>Email:</b> {{ usuario.email }}</p>
            <a href="{% url 'perfil_usuario' usuario.id %}">Ver Perfil de Usuario</a>
        </li>
        <hr>
    {% endfor %}
</ul>
{% endblock %}

fitness/templates/url-anteriores/nuevo.html
{% extends 'principal.html' %}

{% block content %}
    {% block busqueda %}
        <h2>{{ texto_busqueda|linebreaksbr }}</h2>
    {% endblock %}

    {% block resultados %}
        {% for ejercicio in ejercicios_mostrar %}
            <!-- Mostrar detalles del ejercicio -->
            llll
        {% endfor %}
    {% endblock %}
{% endblock %}

fitness/templates/url-anteriores/perfil_usuario.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
<br>
  <h2>PERFIL DE USUARIO</h2>
{% endblock %}

{% block contenido %}
    <img src="{% static 'imagenes/harry.png'%}" width="350" height="300"></img>
    <p>Nombre:{{ perfil_mostrar.usuario.nombre }}</p>
    <p>Edad: {{ perfil_mostrar.edad }}</p>
    <p>Altura: {{ perfil_mostrar.altura }}</p>
    <p>Peso: {{ perfil_mostrar.usuario.nombre }}</p>
{% endblock %}

fitness/templates/url-anteriores/rutina_diaria_usuario_con_H.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
<br>
  <h2>RUTINA DIARIA DE USUARIOS, CUYO NOMBRE ENPIEZA CON H:</h2>
{% endblock %}

{% block contenido%}
    <ul>
        {% for rutina_diaria in rutinas_diarias %}
            <li>
                <p><strong>Nombre:</strong>{{ rutina_diaria.usuario.nombre }}</p>
                <p><strong>Fecha:</strong> {{ rutina_diaria.fecha }}</p>
                <p><strong>Descripción:</strong> {{ rutina_diaria.descripcion }}</p>
                <p><strong>Duración (minutos):</strong> {{ rutina_diaria.duracion }}</p>
                <h3>Ejercicios:</h3>
                <ul>
                    {% for ejercicio in rutina_diaria.ejercicios.all %}
                        <li>{{ ejercicio.nombre }}
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock%}

fitness/templates/url-anteriores/url1.html
<html>
    <body>
        <h1>APLICACION FITNESS</h1>
        <h2>Listados de enlaces</h2>
        <div>
            <h3>
                Ultimo voto:
            </h3>
           <ul>
                <li><p>Nombre:{{usuario_mostrar.u_creador}}</p>
                    <p>Puntuación:{{usuario_mostrar.puntuacion}}</p>
                    <p>Comentario:{{usuario_mostrar.comentario}}</p>
                    <p>Fecha:{{usuario_mostrar.fecha}}</p>
                    <p>Ejercicio:{{usuario_mostrar.ejercicio}}</p></li>

           </ul>

        </div>
  

        <footer>
            <p>Pie de página &copy; 2023 Gabriela Pinzón</p>
        </footer>
    </body>

</html>

fitness/templates/url-anteriores/url2.html
<!DOCTYPE html>
<html>
<head>
    <title>Ejercicios con Puntuación 3</title>
</head>
<body>
    <h1>Ejercicios con Puntuación 3:{{ usuario }}</h1>
    
    <ul>
        {% for ejercicio in ejercicios_mostrar %}
            <li>
                <h2>{{ ejercicio.titulo }}</h2>
                <p>{{ ejercicio.descripcion }}</p>
                <p>Puntuación: {{ ejercicio.voto.puntuacion }}</p>
                <!-- Aquí puedes mostrar otros detalles del ejercicio -->
            </li>
        {% empty %}
            <li>No se encontraron ejercicios con puntuación 3 realizados por {{ usuario }}</li>
        {% endfor %}
    </ul>
</body>
</html>

fitness/templates/url-anteriores/url3.html
<!DOCTYPE html>
<html>
<head>
    <title>Usuarios sin Votos</title>
</head>
<body>
    <h1>Usuarios o Clientes sin Votos</h1>
    
    <ul>
        {% for usuario in usuarios_sin_votos %}
            <li>
                <h2>{{ usuario.nombre }}</h2>
                <p>Email: {{ usuario.email }}</p>
                <p>Otra información del usuario o cliente</p>
            </li>
        {% empty %}
            <li>No se encontraron usuarios o clientes sin votos.</li>
        {% endfor %}
    </ul>
</body>
</html>

fitness/templates/url-anteriores/url4.html
<!DOCTYPE html>
<html>
<head>
    <title>Cuentas Bancarias</title>
</head>
<body>
    <h1>Cuentas Bancarias</h1>
    <ul>
        {% for cuenta in cuenta_mostrar %}
            <li>
                Propietario: {{ cuenta.titular.nombre }}<br>
                Banco: {{ cuenta.banco }}<br>
                Número de cuenta: {{ cuenta.numero_cuenta }}<br>
            </li>
        {% empty %}
            <li>No se encontraron cuentas que cumplan con los criterios.</li>
        {% endfor %}
    </ul>
</body>
</html>

fitness/templates/url-anteriores/usuarios_sin_comentarios.html
{% extends 'fitness/principal.html' %}
{% load static%}

{% block cabecera%}
{% endblock %}

{% block contenido%}
<BR>
    <h1>USUARIOS SIN COMENTARIOS:</h1>
    <ul>
        {% for usuario in usuarios_sin_comentarios %}
            <li>{{ usuario.nombre }}</li>
        {% empty %}
            <p>Lo sentimos pero no hay usuarios.</p>
        {% endfor %}
    </ul>
{% endblock%}